### PR TITLE
test: Added test for user plugin

### PR DESCRIPTION
**Pull request by harsh-2711**
### What does this do / why do we need it?
Adds tests for user plugin methods

### What should your reviewer look out for in this PR?
Added tests for methods in `service.go` file in `dao_test.go`

### Do you need help or clarification on anything?
No

### Which issue(s) does this PR fix?
Fixes: #19

### CODE REVIEW

**Comment by harsh-2711** [comment]
@jeet-parekh I want some help for writing tests of getRawUser and getRawUsers methods. I am getting the same error as in PR #25 i.e. `json: cannot unmarshal number into Go struct field SearchHits.hits.total of type elastic.TotalHits`

**Comment by jeet-parekh** [comment]
@harsh-2711, let's keep the discussion at PR #25.

**Comment by harsh-2711** [comment]
@bietkul @jeet-parekh Can you help me out with methods in middleware.go?

**Comment by siddharthlatest** [comment]
closing this, as we have moved to using end-to-end tests instead of mock tests.

**Pull request closed without merging**
